Repository exelearning/exelearning, pull requests merged in 2025-09, with the labels that each got.

#235 Improved style update and test
  src/Service/net/exelearning/Service/FilesDir/FilesDirService.php
  src/Util/net/exelearning/Util/FileUtil.php
  tests/Unit/Service/FilesDirServiceTest.php
Labels: bug, high priority

#234 Electron: Desktop-like Save / Open / Export in Offline Mode, plus Offline Tests
  .github/workflows/ci.yml
  Makefile
  composer.json
  main.js
  package.json
  phpunit.xml.dist
  preload.js
  public/app/app.js
  public/app/workarea/interface/elements/saveButton.js
  public/app/workarea/menus/navbar/items/navbarFile.js
  public/app/workarea/mock-electron-api.js
  public/app/workarea/modals/modals/pages/modalOpenUserOdeFiles.js
  public/app/workarea/project/projectManager.js
  templates/workarea/menus/menuNavbar.html.twig
  tests/E2E/MenuOnlineFunctionalityTest.php
  tests/E2E/MenuOnlineVisibilityTest.php
  tests/E2E/Offline/MenuOfflineFunctionalityTest.php
  tests/E2E/Offline/MenuOfflineVisibilityTest.php
  tests/E2E/Offline/OfflineModePantherTest.php
  tests/electron/app.spec.js
  tests/electron/file-menu.spec.js
  translations/en.json
Labels: javascript, installers, ui

#241 New export option – Export to Folder (Unzipped Website)
  composer.json
  main.js
  preload.js
  public/app/workarea/menus/navbar/items/navbarFile.js
  public/app/workarea/mock-electron-api.js
  templates/workarea/menus/menuNavbar.html.twig
  tests/E2E/MenuOnlineFunctionalityTest.php
  tests/E2E/Offline/MenuOfflineExportHtmlFolderTest.php
  tests/E2E/Offline/MenuOfflineExportsPackagesTest.php
  tests/E2E/Offline/MenuOfflineFileOpsTest.php
  tests/E2E/Offline/MenuOfflineToolbarAndSaveFlowTest.php
  tests/electron/export-folder.spec.js
  translations/en.json
Labels: enhancement, javascript, installers

#205 Initial version of teacher-mode (WIP)
  public/app/common/common_i18n.js
  public/app/common/exe_export.js
  public/files/perm/themes/base/base/content.css
  public/files/perm/themes/base/test/content.css
  public/style/workarea/base.css
  src/Controller/net/exelearning/Controller/Api/ParameterApiController.php
  src/Properties.php
  src/Util/net/exelearning/Util/ExportXmlUtil.php
Labels: ui

#296 PHP-generated common_i18n.js (#233)
  src/Service/net/exelearning/Service/Api/OdeExportService.php
  src/Util/net/exelearning/Util/Commoni18nUtil.php
Labels: enhancement
